market/cart/urls.py
# pylint: disable=C0103
""" Настройки URL приложения cart """

from django.urls import path

from cart.views import CartView, cart_add, cart_remove

app_name = "cart"

urlpatterns = [
    path("", CartView.as_view(), name="cart"),
    path("add/<int:pk>/", cart_add, name="cart-add"),
    path("remove/<int:pk>/", cart_remove, name="cart-remove"),
]

market/config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = []

urlpatterns += i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path("admin/settings_app/", include("settings_app.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="user")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("discounts/", include("discounts.urls", namespace="discount")),
    path("pay/", include("order.urls", namespace="url")),
    path("", include(("products.urls", "products"), namespace="product")),
    path("", include(("imports.urls", "imports"), namespace="imports")),
    path("comparison/", include(("comparison.urls", "comparison"), namespace="comparison")),
    path("shop/", include(("shops.urls", "shops"), namespace="shop")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/cart/models.py
"""Модели приложения cart"""

from django.db import models
from django.utils.translation import gettext_lazy as _

from accounts.models import User
from shops.models import Offer


class Cart(models.Model):
    """Модель корзины"""

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="carts", verbose_name=_("пользователь"))
    is_active = models.BooleanField(default=True, verbose_name=_("активный"))

    class Meta:
        """Метаданные класса Cart"""

        verbose_name = _("корзина")
        verbose_name_plural = _("корзины")

    def __str__(self):
        return f"Cart {self.user}"


class ProductInCart(models.Model):
    """Модель товара в корзине"""

    offer = models.ForeignKey(Offer, on_delete=models.CASCADE, verbose_name=_("предложения"))
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="offers", verbose_name=_("корзина"))
    quantity = models.PositiveIntegerField(verbose_name=_("количества"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("дата создания"))

    class Meta:
        """Метаданные класса ProductInCart"""

        verbose_name = _("товар в корзине")
        verbose_name_plural = _("товары в корзине")
        ordering = ("-created_at",)

    def __str__(self):
        return f"Product {self.offer.product} in cart {self.cart}"

market/shops/models.py
"""Django-модели приложения shops"""
import os

from django.conf import settings

from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from accounts.models import User


def shop_logo_directory_path(instance: "Shop", filename: str) -> str:
    """Функция, гененрирующая путь, по которому будет храниться логотип компании-продавца"""
    return os.path.join(settings.MEDIA_ROOT, f"shops/shop_{instance.name}/{filename}")


class Shop(models.Model):
    """Модель магазина, который является продавцом на маркетплейсе Megano"""

    name = models.CharField(max_length=512, verbose_name=_("название"), blank=True, null=True)
    contact_info = models.CharField(max_length=512, verbose_name=_("контактная информация"), blank=True, null=True)
    description = models.TextField(verbose_name=_("описание"), blank=True, null=True)
    products = models.ManyToManyField(
        "products.Product",
        through="Offer",
        related_name="shops",
        verbose_name=_("товары в магазине"),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=_("пользователь"))
    logo = models.ImageField(
        upload_to=shop_logo_directory_path,
        validators=[FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png"])],
        verbose_name=_("логотип компании"),
        blank=True,
        null=True,
    )

    class Meta:
        """Метаинформация о модели 'Магазин'."""

        verbose_name = _("продавец")
        verbose_name_plural = _("продавцы")

    def __str__(self):
        return f"{self.name}"


class Offer(models.Model):
    """Предложение магазина"""

    shop = models.ForeignKey(Shop, on_delete=models.CASCADE, verbose_name=_("магазин"))
    product = models.ForeignKey("products.Product", on_delete=models.CASCADE, verbose_name=_("продукт"))
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name=_("цена"))
    remains = models.IntegerField(default=0, verbose_name=_("осталось"))

    class Meta:
        """Метаинформация о модели 'Предложение'."""

        constraints = [models.UniqueConstraint("shop", "product", name="unique_product_in_shop")]
        verbose_name = _("предложения")
        verbose_name_plural = _("предложение")

market/cart/forms.py
""" Формы приложения Cart """

from django import forms


class CartAddProductForm(forms.Form):
    """Форма для обновления количества товаров в корзине"""

    quantity = forms.IntegerField(
        min_value=1,
        max_value=21,
        widget=forms.TextInput(
            attrs={
                "class": "Amount-input form-input",
                "readonly": True,
            }
        ),
        label="",
    )
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

market/cart/views.py
""" Модуль с представлениями приложения cart """
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from cart.cart import CartInstance
from cart.forms import CartAddProductForm
from shops.models import Offer


class CartView(TemplateView):
    """Представление для отображения корзины"""

    template_name = "cart/cart.jinja2"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = CartInstance(self.request)

        for item in cart:
            item["form"] = CartAddProductForm(initial={"quantity": item["quantity"], "update": False})
        context["cart"] = cart
        return context


@require_POST
def cart_add(request: HttpRequest, pk: int) -> HttpResponse:
    """Добавление товара в корзину"""

    cart = CartInstance(request)
    offer = get_object_or_404(Offer, id=pk)
    form = CartAddProductForm(request.POST)
    new_offer_id = request.POST["offer"]
    new_offer = Offer.objects.get(id=new_offer_id)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=offer.product, offer=new_offer, quantity=cd["quantity"], update_quantity=cd["update"])
    else:
        return HttpResponse(form.errors.values())
    if new_offer != offer:
        cart.remove(offer)

    return redirect(request.META.get("HTTP_REFERER"))


@require_POST
def cart_remove(request, pk):
    """Удаление товара из корзины"""
    cart = CartInstance(request)
    offer = get_object_or_404(Offer, id=pk)
    cart.remove(offer)
    return redirect("cart:cart")

market/templates/cart/cart.jinja2
{% extends 'base.jinja2' %}

{% block title %}
    Корзина
{% endblock %}

{% block content %}
    <div class="Middle Middle_top">
        <div class="Section">
            <div class="wrap">
                {% for item in cart %}
                    {% with offer=item["offer"] %}
                        <form class="form" id="cart_form" method="post" action="{{ url('cart:cart-add', offer.id) }}">
                            <div class="Cart-product">
                                <div class="Cart-block Cart-block_row">
                                    <div class="Cart-block Cart-block_pict">
                                        <a class="Cart-pict"
                                           href="{{ url('products:product-details', offer.product.id) }}">
                                            <img class="Cart-img"
                                                 src='{{ offer.product.images.first().image.url }}'
                                                 alt="{{ offer.product.name }}'s image"/>
                                        </a>
                                    </div>
                                    <div class="Cart-block Cart-block_info">
                                        <a class="Cart-title"
                                           href="{{ url('products:product-details', offer.product.id) }}">{{ offer.product.name }}</a>
                                        <div class="Cart-desc">{{ offer.product.description|truncate(40) }}
                                        </div>
                                    </div>
                                    <div class="Cart-block Cart-block_shop">
                                        <div class="Cart-price" id="product-price">
                                            <p><select size="3" name="offer">
                                                {% with offers=item["offer"].product.offer_set.all().order_by("price") %}
                                                    {% for offer in offers %}
                                                        {% if item["offer"] == offer %}
                                                            <option selected
                                                                    value="{{ offer.id }}">{{ offer.shop.name }}:
                                                                {{ offer.price }}</option>
                                                        {% else %}
                                                            <option value="{{ offer.id }}">{{ offer.shop.name }}:
                                                                {{ offer.price }}</option>
                                                        {% endif %}
                                                    {% endfor %}
                                                {% endwith %}
                                            </select></p>
                                        </div>
                                    </div>
                                    <div class="Cart-block Cart-block_price">
                                        <div class="Cart-price" id="product-price">{{ item["price"] }}
                                        </div>
                                    </div>
                                </div>
                                <div class="Cart-block Cart-block_row">
                                    <div class="Cart-block Cart-block_seller">
                                        <!-- - var options = setOptions(items, ['value', 'selected', 'disabled']);-->
                                    </div>
                                    <div class="Cart-block Cart-block_amount">
                                        <div class="Cart-amount">
                                            <div class="Amount">
                                                {% csrf_token %}
                                                <button class="Amount-remove" type="button">
                                                </button>
                                                {{ item.form }}
                                                <button class="Amount-add" type="button">
                                                </button>
                                                <input type="submit" value="&#8634;" name="product_quantity">
                                                <input type="hidden" class="product_id" id="product_id"
                                                       name="product_id"
                                                       value="{{ offer.id }}">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="Cart-block Cart-block_delete">
                                        <input class="Cart-delete" type="image"
                                               formaction="{{ url('cart:cart-remove', offer.id) }}"
                                               src="{{ static('img/icons/card/delete.svg') }}" alt="cart.svg">
                                    </div>
                                </div>
                            </div>

                        </form>
                    {% endwith %}
                {% endfor %}
                <div class="Cart-total">
                    {% with total_price = cart.get_total_price() %}
                        {% if total_price > 0 %}
                            <div class="Cart-block Cart-block_total">
                                <strong class="Cart-title">{{ _('Итого без скидки: ') }}
                                </strong><span class="Cart-price">{{ cart.get_total_price_without_discount() }}</span>
                            </div>
                            <div class="Cart-block Cart-block_total">
                                <strong class="Cart-title">{{ _('Итого со скидкой: ') }}
                                </strong><span class="Cart-price">{{ total_price }}</span>
                            </div>
                            <div class="Cart-block">
                                {% if request.user.is_authenticated %}
                                    <a class="btn btn_success btn_lg"
                                       href="{{ url('url:step1') }}">{{ _('Оформить заказ') }}</a>
                                {% else %}
                                    <a class="btn btn_success btn_lg"
                                       href="{{ url('accounts:login') }}">{{ _('Оформить заказ') }}</a>
                                {% endif %}
                            </div>
                        {% else %}
                            <strong class="Cart-title">{{ _('Ваша корзина пуста. Перейдите в') }} <a
                                    href="{{ url('product:catalog') }}">{{ _('каталог') }}</a>,
                                {{ _('чтобы совершить покупки') }}</strong>
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}