market/cart/urls.py
# pylint: disable=C0103
""" Настройки URL приложения cart """

from django.urls import path

from cart.views import CartView, cart_add, cart_remove

app_name = "cart"

urlpatterns = [
    path("", CartView.as_view(), name="cart"),
    path("add/<int:pk>/", cart_add, name="cart-add"),
    path("remove/<int:pk>/", cart_remove, name="cart-remove"),
]

market/config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = []

urlpatterns += i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path("admin/settings_app/", include("settings_app.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="user")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("discounts/", include("discounts.urls", namespace="discount")),
    path("pay/", include("order.urls", namespace="url")),
    path("", include(("products.urls", "products"), namespace="product")),
    path("", include(("imports.urls", "imports"), namespace="imports")),
    path("comparison/", include(("comparison.urls", "comparison"), namespace="comparison")),
    path("shop/", include(("shops.urls", "shops"), namespace="shop")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/order/urls.py
# pylint: disable=C0103
""" Модуль для определения URL-путей приложения orders """

from django.urls import path
from .views import (
    FirstOrderView,
    SecondOrderView,
    ThirdOrderView,
    FourStepView,
    OrderListView,
    OrderDetailView,
)

app_name = "order"

urlpatterns = [
    path("step/", FirstOrderView.as_view(), name="step1"),
    path("step1/", SecondOrderView.as_view(), name="step2"),
    path("step2/", ThirdOrderView.as_view(), name="step3"),
    path("step3/", FourStepView.as_view(), name="step4"),
    path("history_order/", OrderListView.as_view(), name="history_order"),
    path("history_order/<int:pk>/", OrderDetailView.as_view(), name="detail_order"),
]

market/order/models.py
"""
Модуль, содержащий модели для управления заказами в приложении.
"""
from django.db import models
from django.utils.translation import gettext_lazy as _

from accounts.models import User
from cart.models import Cart


class PaymentTypes(models.TextChoices):
    """
    Типы оплаты для заказов.
    """

    CARD = "card", "Онлайн картой"


class OrderStatus(models.TextChoices):
    """
    Статусы заказов.
    """

    CREATED = "created", "Создан"
    PAID = "paid", "Оплачен"
    NOT_PAID = "not_paid", "Не оплачен"


class DeliveryTypes(models.TextChoices):
    """
    Типы доставки для заказов.
    """

    REGULAR = "regular", "Обычная доставка"
    EXPRESS = "express", "Экспресс-доставка"


class Order(models.Model):
    """Модель заказа"""

    name = models.TextField(max_length=20, blank=False, null=False, verbose_name=_("имя"))
    phone = models.IntegerField(verbose_name=_("телефон"))
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_("пользователь"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("дата создания"))
    delivery_type = models.CharField(
        max_length=50,
        choices=DeliveryTypes.choices,
        verbose_name="delivery type",
        blank=False,
        default=DeliveryTypes.REGULAR,
    )
    city = models.CharField(max_length=50, verbose_name=_("город"))
    address = models.CharField(max_length=255, verbose_name=_("адрес"))
    payment_type = models.CharField(
        max_length=50,
        choices=PaymentTypes.choices,
        blank=False,
        default=PaymentTypes.CARD,
        verbose_name=_("Способ оплаты"),
    )
    status = models.CharField(
        max_length=15, choices=OrderStatus.choices, default=OrderStatus.CREATED, verbose_name=_("статус")
    )
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE, verbose_name=_("корзина"))
    total_price = models.DecimalField(max_digits=12, decimal_places=2, verbose_name=_("Общая стоимость"))

    class Meta:
        """Определение мета-атрибутов модели заказа."""

        db_table = "order"
        verbose_name = _("заказ")
        verbose_name_plural = _("заказы")

market/order/forms.py
"""
Модуль, содержащий формы для многоэтапной обработки заказов.

Эти формы предназначены для использования в процессе создания заказа
поэтапно, где каждая форма представляет собой отдельный этап процесса.

Классы:
    FirstStepForm: Форма для сбора имени и номера телефона.
    SecondStepForm: Форма для сбора города, адреса и типа доставки.
    ThirdStepForm: Форма для сбора типа оплаты.
"""

from django import forms
from .models import Order


class FirstStepForm(forms.ModelForm):
    """Форма для сбора имени и номера телефона."""

    class Meta:
        """Метаданные о форме"""

        model = Order
        fields = ("name", "phone")


class SecondStepForm(forms.ModelForm):
    """Форма для сбора информации о городе, адресе и типе доставки."""

    class Meta:
        """Метаданные о форме"""

        model = Order
        fields = ("city", "address", "delivery_type")


class ThirdStepForm(forms.ModelForm):
    """Форма для сбора информации о типах оплаты"""

    class Meta:
        """Метаданные о форме"""

        model = Order
        fields = ("payment_type",)

market/order/views.py
import uuid
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView

from accounts.models import User
from cart.models import Cart, ProductInCart
from accounts.group_mixins import BuyersRequiredMixin
from .forms import FirstStepForm, SecondStepForm, ThirdStepForm
from .models import Order
from .service import OrderService
from dotenv import load_dotenv
from yookassa import Configuration, Payment
import os
from .service import translate
from cart.cart import CartInstance
from django.db.models import F
from shops.models import Offer

load_dotenv()

Configuration.account_id = os.getenv('SHOP_ID')
Configuration.secret_key = os.getenv('SECRET_KEY')


class FirstOrderView(LoginRequiredMixin, BuyersRequiredMixin, FormView):
    form_class = FirstStepForm

    template_name = "order/order.jinja2"
    success_url = reverse_lazy("url:step2")

    def form_valid(self, form):
        self.request.session[self.request.user.id] = {}
        self.request.session[self.request.user.id] = {
            "name": form.cleaned_data["name"],
            "phone": form.cleaned_data["phone"],
        }

        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _("не верный ввод полей"))
        return super().form_invalid(form)


class SecondOrderView(LoginRequiredMixin, BuyersRequiredMixin, FormView):
    template_name = "order/order_2.jinja2"
    success_url = reverse_lazy("url:step3")
    form_class = SecondStepForm

    def form_valid(self, form):
        user_data = self.request.session.get(f"{self.request.user.id}")
        user_data["address"] = form.cleaned_data["address"]
        user_data["city"] = form.cleaned_data["city"]
        user_data["delivery_type"] = form.cleaned_data["delivery_type"]
        self.request.session[f"{self.request.user.id}"] = user_data
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _("не верный ввод полей"))
        return super().form_invalid(form)


class ThirdOrderView(LoginRequiredMixin, BuyersRequiredMixin, FormView):
    template_name = "order/order_3.jinja2"
    form_class = ThirdStepForm
    success_url = reverse_lazy("url:step4")

    def form_valid(self, form):
        user_data = self.request.session.get(f"{self.request.user.id}")
        user_data["payment_type"] = form.cleaned_data["payment_type"]
        self.request.session[f"{self.request.user.id}"] = user_data

        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _("не верный ввод полей"))
        return super().form_invalid(form)


class FourStepView(LoginRequiredMixin, BuyersRequiredMixin, ListView):
    template_name = "order/order_4.jinja2"
    model = ProductInCart

    def post(self, request, *args, **kwargs):
        payment_type = request.POST.get('yookassa-payment')
        cartt = Cart.objects.get(user=request.user.id)
        user = User.objects.get(pk=request.user.id)
        cart = CartInstance(request)
        products = cart.get_offers_with_quantity()
        for product, count in products:
            Offer.objects.filter(id=product.id).update(remains=F('remains') - count)
        Order.objects.update_or_create(
            cart=cartt,
            user=user,
            defaults={
                "phone": request.session[f"{self.request.user.id}"]["phone"],
                "name": request.session[f"{self.request.user.id}"]["name"],
                "delivery_type": request.session[f"{self.request.user.id}"]["delivery_type"],
                "city": request.session[f"{self.request.user.id}"]["city"],
                "address": request.session[f"{self.request.user.id}"]["address"],
                "payment_type": request.session[f"{self.request.user.id}"]["payment_type"],
                "total_price": cart.get_total_price(),
            },
        )
        match payment_type:
            case "yookassa-payment":
                idempotence_key = uuid.uuid4()
                currency = 'RUB'
                description = 'Товары в корзине'
                payment = Payment.create({
                    "amount": {
                        "value": cart.get_total_price(),
                        "currency": currency
                    },
                    "confirmation": {
                        "type": "redirect",
                        "return_url": request.build_absolute_uri(reverse('user:main')),
                    },
                    "capture": True,
                    "test": True,
                    "description": description,
                }, idempotence_key)

                confirmation_url = payment.confirmation.confirmation_url
                self.request.session[self.request.user.id] = {}
                self.request.session[self.request.user.id] = {"id": payment.id}

                return redirect(confirmation_url)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = Cart.objects.get(user=self.request.user.id)
        delivery_type, pay_type = translate(self.request.session[f"{self.request.user.id}"]["delivery_type"])
        context["delivery_type"] = delivery_type
        context["name"] = self.request.session[f"{self.request.user.id}"]["name"]
        context["phone"] = self.request.session[f"{self.request.user.id}"]["phone"]
        context["city"] = self.request.session[f"{self.request.user.id}"]["city"]
        context["address"] = self.request.session[f"{self.request.user.id}"]["address"]
        context["payment"] = pay_type
        context["product"] = ProductInCart.objects.filter(cart=cart)[:3]
        return context


class OrderListView(LoginRequiredMixin, BuyersRequiredMixin, ListView):
    """
    Класс представления для отображения истории заказов.

    Он позволяет аутентифицированным пользователям просматривать свою историю заказов.

    Attributes:
        model (Model): Модель Django для связи с базой данных.
        template_name (str): Имя шаблона, используемого для отображения представления.
        context_object_name (str): Имя объекта контекста для передачи списка заказов в шаблон.
    """

    model = Order
    template_name = "order/order_history.jinja2"
    context_object_name = "orders"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["history"] = OrderService(self.request).get_order_history()
        return context


class OrderDetailView(LoginRequiredMixin, BuyersRequiredMixin, DetailView):
    """
    Класс представления для отображения детальной информации о заказе.

    Пользователи могут просматривать детали конкретного заказа.

    Attributes:
        model (Model): Модель Django для связи с базой данных.
        template_name (str): Имя шаблона, используемого для отображения представления.
    """

    model = Order
    template_name = "order/detail_order.jinja2"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = self.object
        order_service = OrderService(self.request)
        context["order_status"] = order_service.get_status(order)
        context["order"] = order_service.get_order_by_id(order.id)
        return context

market/templates/order/detail_order.jinja2
{% extends 'base.jinja2' %}

{% block title %}
    {{ _('Заказ №') }} {{ order.id }}
{% endblock %}

{% block content %}
    <div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">{{ _('Заказ №') }} {{ order.id }}</h1>
                    <ul class="breadcrumbs Middle-breadcrumbs">
                        <li class="breadcrumbs-item"><a href="{{ url('product:index') }}">{{ _('Главная') }}</a></li>
                        <li class="breadcrumbs-item"><a href="{{ url('order:history_order') }}">{{ _('История заказов') }}</a></li>
                        <li class="breadcrumbs-item breadcrumbs-item_current"><span>{{ _('Заказ №') }} {{ order.id }}</span></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="Section">
            <div class="wrap">
                <div class="Section-content">
                    <div class="Order">
                        <div class="Order-infoBlock">
                            <div class="Order-personal">
                                <div class="row">
                                    <div class="row-block">
                                        <div class="Order-info Order-info_date">
                                            <div class="Order-infoType">{{ _('Дата заказа:') }}</div>
                                            <div class="Order-infoContent">{{ order.created_at.strftime('%d.%m.%Y') }}</div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">{{ _('ФИО') }}:</div>
                                            <div class="Order-infoContent">{{ order.cart.user.username }}</div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">{{ _('E-mail') }}:</div>
                                            <div class="Order-infoContent">{{ order.cart.user.email }}</div>
                                        </div>
                                    </div>
                                    <div class="row-block">
                                        <div class="Order-info Order-info_delivery">
                                            <div class="Order-infoType">{{ _('Тип доставки') }}:</div>
                                            <div class="Order-infoContent">{{ order.get_delivery_type_display() }}</div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">{{ _('Город') }}:</div>
                                            <div class="Order-infoContent">{{ order.city }}</div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">{{ _('Адрес') }}:</div>
                                            <div class="Order-infoContent">{{ order.address }}</div>
                                        </div>
                                        <div class="Order-info Order-info_pay">
                                            <div class="Order-infoType">{{ _('Оплата') }}:</div>
                                            <div class="Order-infoContent">{{ order.get_payment_type_display() }}</div>
                                        </div>
                                        <div class="Order-info Order-info_status">
                                            <div class="Order-infoType">{{ _('Статус') }}:</div>
                                            <div class="Order-infoContent">{{ order.get_status_display() }}</div>
                                        </div>

                                        {% if order.status == 'not_paid' %}
                                            <div class="Order-info Order-info_error">
                                                <div class="Order-infoType">{{ _('Не оплачен') }}</div>
                                                <div class="Order-infoContent">{{ _('Оплата не выполнена.') }}</div>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

market/templates/order/order.jinja2
{% extends "base.jinja2" %}
{% block content %}
<div class="Section-content">
    <form class="form" method="post">
        {% csrf_token %}
        <div class="Order-block Order-block_OPEN" id="step1">
            <header class="Section-header Section-header_sm">
                <h2 class="Section-title">{{ _('Шаг 1. Параметры пользователя ') }}
                </h2>
            </header>
            <div class="row">
                <div class="row-block">
                    <div class="form-group">
                        <label class="form-label" for="name">{{ _('Фио') }}
                        </label>
                        <input class="form-input" id="name" name="name" type="text" required />
                    </div>
                    <div class="form-group">
                        <label class="form-label" for="phone">{{ _('Телефон') }}
                        </label>
                        <input class="form-input" id="phone" name="phone" type="text" required />
                    </div>
                </div>
            </div>
            <div class="Order-footer">
                <button class="btn btn_success" type="submit">{{ _('дальше') }}</button>
            </div>
            {% if messages %}
               {% for message in messages %}
               {{ message }}
               {% endfor %}
            {% endif %}

        </div>
    </form>
</div>

{% endblock %}

market/templates/order/order_2.jinja2
{% extends "base.jinja2" %}
{% block content %}
<div class="Section-columnSection">
    <header class="Section-header">
        <strong class="Section-title">{{ _("Прогресс заполнения") }}
        </strong>
    </header>
    <div class="Section-columnContent">
        <div class="NavigateProfile">
            <ul class="menu menu_vt">
                <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="#step1">{{ _("Шаг 2. Способ доставки") }}</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="Section-content">
    <form class="form" method="post">
        {% csrf_token %}
        <div class="Order-block Order-block_OPEN" id="step1">
            <header class="Section-header Section-header_sm">
                <h2 class="Section-title">{{ _("Шаг 2. Способ доставки") }}
                </h2>
            </header>
            <div class="form-group">
                <div>
                    <label class="toggle">
                        <input type="radio" name="delivery_type" value="regular" checked="checked" /><span class="toggle-box"></span><span class="toggle-text">{{ _("Обычная доставка") }}</span>
                    </label>
                </div>
                <div>
                    <label class="toggle">
                        <input type="radio" name="delivery_type" value="express" /><span class="toggle-box"></span><span class="toggle-text">{{ _("Экспресс доставка") }}</span>
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label class="form-label" for="city">{{  _("Город") }}
                </label>
                <input class="form-input" id="city" name="city" type="text" />
            </div>
            <div class="form-group">
                <label class="form-label" for="address">{{ _("Адрес") }}
                </label>
                <textarea class="form-textarea" name="address" id="address"></textarea>
            </div>
            <div class="Order-footer">
                <button class="btn btn_success" type="submit">{{ _("Дальше") }}</button>
                {% if messages %}
                    {% for message in messages %}
                    {{ message }}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </form>
</div>
{% endblock %}

market/templates/order/order_3.jinja2
{% extends "base.jinja2" %}
{% block content %}
<div class="Section-columnSection">
    <header class="Section-header">
        <strong class="Section-title">{{  _("Прогресс заполнения") }}
        </strong>
    </header>
    <div class="Section-columnContent">
        <div class="NavigateProfile">
            <ul class="menu menu_vt">
                <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="#step1">{{ _("Шаг 3. Способ оплаты") }}</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="Section-content">
    <form class="form" method="post">
        {% csrf_token %}
        <div class="Order-block Order-block_OPEN" id="step1">
            <header class="Section-header Section-header_sm">
                <h2 class="Section-title">{{  _("Шаг 3. Способ оплаты") }}
                </h2>
            </header>
            <div>
                <label class="toggle">
                    <input type="radio" name="payment_type" value="card" checked="checked" /><span class="toggle-box"></span><span class="toggle-text">{{  _("Онлайн картой") }}</span>
                </label>
            </div>
            <div class="Order-footer">
                <button class="btn btn_success" type="submit">{{ _("Дальше") }}</button>
            </div>
            {% if messages %}
                {% for message in messages %}
                {{ message }}
                {% endfor %}
            {% endif %}
        </div>
    </form>
</div>
{% endblock %}

market/templates/order/order_4.jinja2
{% extends "base.jinja2" %}
{% block content %}
<div class="Section-columnSection">
    <header class="Section-header">
        <strong class="Section-title">{{  _("Прогресс заполнения") }}
        </strong>
    </header>
    <div class="Section-columnContent">
        <div class="NavigateProfile">
            <ul class="menu menu_vt">
                <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="#step1">{{ _("Шаг 4. Подтверждение заказа") }}</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="Section-content">
    <div class="Order-block Order-block_OPEN" id="step1">
        <header class="Section-header Section-header_sm">
            <h2 class="Section-title">{{ _("Шаг 4. Подтверждение заказа") }}
            </h2>
        </header>
        <div class="Order-infoBlock">
            <div class="Order-personal">
                <div class="row">
                    <div class="row-block">
                        <div class="Order-info">
                            <div class="Order-infoType">{{ _("имя") }}:
                            </div>
                            <div class="Order-infoContent">{{ name }}
                            </div>
                        </div>
                        <div class="Order-info">
                            <div class="Order-infoType">{{ _("Телефон") }}:
                            </div>
                            <div class="Order-infoContent">{{ phone }}
                            </div>
                        </div>
                        <div class="Order-info">
                            <div class="Order-infoType">{{ _("E-mail") }}:
                            </div>
                            <div class="Order-infoContent">{{ request.user }}
                            </div>
                        </div>
                    </div>
                    <div class="row-block">
                        <div class="Order-info Order-info_delivery">
                            <div class="Order-infoType">{{ _("Тип доставки") }}:
                            </div>
                            <div class="Order-infoContent">{{ delivery_type }}
                            </div>
                        </div>
                        <div class="Order-info">
                            <div class="Order-infoType">{{ _("Город") }}:
                            </div>
                            <div class="Order-infoContent">{{ city }}
                            </div>
                        </div>
                        <div class="Order-info">
                            <div class="Order-infoType">{{ _("Адрес") }}:
                            </div>
                            <div class="Order-infoContent">{{ address }}
                            </div>
                        </div>
                        <div class="Order-info Order-info_pay">
                            <div class="Order-infoType">{{ _("Оплата") }}:
                            </div>
                            <div class="Order-infoContent"> {{ payment }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="Cart Cart_order">
                {% if product %}
                {% for i in  product  %}
                <div class="Cart-product">
                    {% with first_image=i.offer.product.images.first %}
                    <div class="Cart-block Cart-block_row">
                        <div class="Cart-block Cart-block_pict"><a class="Cart-pict" href="#"><img class="Cart-img" src="{{ i.offer.product.images.first().image.url }}" alt="card.jpg" /></a>
                        </div>
                        {% endwith %}
                        <div class="Cart-block Cart-block_info"><a class="Cart-title" href="#">{{i.offer.product.name}}</a>
                            <div class="Cart-desc">{{i.offer.product.description}}
                            </div>
                        </div>
                        <div class="Cart-block Cart-block_price">
                            <div class="Cart-price">{{i.offer.price }}
                            </div>
                        </div>
                    </div>
                    <div class="Cart-block Cart-block_row">
                        <div class="Cart-block Cart-block_amount">{{ i.quantity }} {{ _("шт.") }}
                        </div>
                    </div>
                </div>
                {% endfor %}
                <form class="form"  method="post">{% csrf_token %}
                    <div class="Cart-block">
                        <button class="btn btn_primary btn_lg" name="yookassa-payment" value="yookassa-payment" type="submit">{{ _("Оплатить") }}</button>
                    </div>
                </form>
                </div>
            </div>
        </div>
        {% else %}
        <div>
            <p>{{ _("нет заказов") }}</p>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

market/templates/order/order_history.jinja2
{% extends 'base.jinja2' %}

{% block title %}
    {% trans %}История заказов{% endtrans %}
{% endblock %}

{% block content %}
    <div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">{% trans %}История заказов{% endtrans %}</h1>
                    <ul class="breadcrumbs Middle-breadcrumbs">
                        <li class="breadcrumbs-item"><a href="{{ url('product:index') }}">{% trans %}Главная{% endtrans %}</a></li>
                        <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% trans %}История заказов{% endtrans %}</span></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                <div class="Section-column">
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">{% trans %}Навигация{% endtrans %}</strong>
                        </header>
                        <div class="Section-columnContent">
                            <div class="NavigateProfile">
                                <ul class="menu menu_vt">
                                    <li class="menu-item"><a class="menu-link" href="{{ url('accounts:main') }}">{% trans %}Личный кабинет{% endtrans %}</a></li>
                                    <li class="menu-item"><a class="menu-link" href="{{ url('accounts:profile') }}">{% trans %}Профиль{% endtrans %}</a></li>
                                    <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{{ url('order:history_order') }}">{% trans %}История заказов{% endtrans %}</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Section-content">
                    <header class="Section-header">
                        <h2 class="Section-title">{{ _('Список заказов') }}</h2>
                    </header>
                    {% if orders %}
                        <ul>
                            {% for order in orders %}
                               <li><a href="{{ url('order:detail_order', pk=order.id) }}">{{ _('Заказ №') }} {{ order.id }} - {{ order.created_at }}</a></li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>{% trans %}У вас еще нет заказов.{% endtrans %}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}